HouseServer/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

import accounts

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'HouseServer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/', include('api.urls')),

    url(r'^', include('survey.urls', namespace="survey")),
)

api/urls.py
import views
from rest_framework.routers import DefaultRouter
from django.conf.urls import patterns, url, include

router = DefaultRouter()
router.register(r'stamp', views.StampViewSet)
router.register(r'description', views.SensorViewSet)
router.register(r'data', views.DataViewSet)


#Define URLs here
urlpatterns = patterns('',
    url(r'^', include(router.urls))
)

survey/urls.py
import views

from django.conf.urls import patterns, url

#Define URLs here
urlpatterns = patterns(
    # /index/
    url(r'^index/$', views.index, name='index1'),

    # /instrument/1/
    url(r'^instrument/(?P<id>\d+)/$', views.instrumentDetail, name="InstrumentDetailed"),
    # /instrument/
    url(r'^instrument/$', views.instrument, name='InstrumentAll'),

    # /stamp/1
    url(r'^stamp/detail/(?P<id>\d+)/$', views.timestampDetail, name="TimestampDetailed"),
    # /stamp/find/
    url(r'stamp/find/$', views.find, name="TimeStampfind"),
    # /stamp/
    url(r'^stamp/$', views.timestamp, name="TimestampGeneral"),

    # /generate/
    url(r'^generate/', views.generate, name="generate"),

    # /download/10/144/
    url(r'^download/(?P<amount>\d+)/(?P<interval>\d+)/$', views.download, name="Download2"),
    # /download/
    url(r'^download/$', views.download, name="Download"),
    # /
    url(r'^$', views.index, name='index'),
)

survey/models.py
from django.db import models

# Create your models here


class TimeStamp(models.Model):
    stamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.stamp)

    class Meta:
        ordering = ("-stamp",)

class SensorDescription(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    unit = models.CharField(max_length=10)
    dui = models.CharField(max_length=32, null=True)

    def __str__(self):
        return self.name

class SensorData(models.Model):
    relatedStamp = models.ForeignKey(TimeStamp)
    relatedSensor = models.ForeignKey(SensorDescription)
    data = models.CharField(max_length=10)

    def __str__(self):
        return str(self.relatedSensor.name + " " + str(self.relatedSensor.id) + " op " + str(self.relatedStamp.stamp))


class Interval(models.Model):
    value = models.IntegerField()
    name = models.CharField(max_length=12)

    def __str__(self):
        return str(self.name)

survey/views.py
import datetime
import random
import csv
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from models import TimeStamp, SensorDescription, SensorData
# Create your views here.
def index(request):
    """
    Lists latest instrument measurements
    """
    try:
        latestStamp = TimeStamp.objects.order_by('-pk')[0]
    except:
        raise Http404
    #Get all timestamps, order them by latest, and pick the first object

    relatedData = SensorData.objects.filter(relatedStamp_id = latestStamp.id)
    #Get all data that has the latest timestamps id as relatedStamp

    context = { 'data': relatedData, 'stampTime' : latestStamp.stamp.time(), "stampDate" : latestStamp.stamp.date()}
    return render(request, 'survey/index.html', context )

def instrument(request, sort=1):
    """
    Lists all instruments
    """

    instruments = SensorDescription.objects.all()
    #Get all sensors in the database

    latestStamp = TimeStamp.objects.order_by('-pk')[0]

    metingen = SensorData.objects.filter(relatedStamp_id=latestStamp.id)

    context = {'instruments' : instruments, 'data': metingen}
    #Set context for template calls

    return render(request, 'survey/instrument.html', context)


def getSpecificPost(get):
    try:
        first = int(get['start'])
    except:
        first = 1
    try:
        last = int(get['end'])
    except:
        last = 50
    try:
        sort = int(get['sorting'])
    except:
        sort = 1

    return first, last, sort


def instrumentDetail(request, id):
    """
    Lists all measurements from a specific instrument
    """

    if request.POST:
        # Handle forms
        get = request.POST

        if get["action"] == 'download':
            first, last, sort = getSpecificPost(get)
            # Als er gedownload moet worden

            relatedData = SensorData.objects.filter(relatedSensor_id = id).order_by('-id')[first:last*sort:sort]

            relatedSensor = get_object_or_404(SensorDescription, pk=id)
            # Ophalen Data

            response = HttpResponse(content_type="text/csv")
            response['Content-Disposition'] = 'attachment; filename="%s.csv"' % str(datetime.datetime.now())
            # Schrijven resposnie

            writer = csv.writer(response, delimiter=';')
            # CSVschrijver openen

            writer.writerow(["Tijdstip", "%s (%s)" % (relatedSensor.name, relatedSensor.unit)])

            for row in relatedData:
                writer.writerow([row.relatedStamp.stamp, row.data])

            return response

        elif get["action"] == "specify":
        # Specifieke meetgegevens pakken
            first, last, sort = getSpecificPost(get)

            relatedData = SensorData.objects.filter(relatedSensor_id = id).order_by('-id')[first:last * sort:sort]
            #Get all data related to the instrument

            relatedSensor = get_object_or_404(SensorDescription, pk=id)
            #Get the sensor description, or 404 otherwise

            context = {'sensor' : relatedSensor, 'data': relatedData, "first": first, "last" : last,"sort":sort }

            return render(request, 'survey/instrumentDetail.html', context)


    relatedData = SensorData.objects.filter(relatedSensor_id = id).order_by('-id')[:6]
    #Get all data related to the instrument, and latest 6

    relatedSensor = get_object_or_404(SensorDescription, pk=id)
    #Get the sensor description, or 404 otherwise

    context = {'sensor' : relatedSensor, 'data': relatedData}

    return render(request, 'survey/instrumentDetail.html', context)


def timestamp(request):
    """
    Lists latest timestamp, with link to details
    """

    if request.POST:
        post = request.POST

        if post['action'] == "download":
            first, last, sort = getSpecificPost(post)
            # Get POST variables

            timestamps = TimeStamp.objects.all()[first:last*sort:sort]
            #timestamps.order_by("-pk")
            # Get Timestamps

            sensors = SensorDescription.objects.all().order_by("pk")

            response = HttpResponse(content_type="text/csv")
            response['Content-Disposition'] = 'attachment; filename="%s.csv"' % str(datetime.datetime.now())
            # Schrijven resposnie

            writer = csv.writer(response, delimiter=';')
            # CSVschrijver openen

            sensorRow = ["Timestamp"]

            for sensor in sensors:
                sensorRow.append("%s (%s)" %(sensor.name , sensor.unit))

            writer.writerow(sensorRow)

            for stamp in timestamps:
                dataRow = [stamp]

                data = SensorData.objects.filter(relatedStamp_id=stamp.id)

                for row in data:
                    dataRow.append(row.data)

                writer.writerow(dataRow)

            return response

        elif post['action'] == "specify":
            first, last, sort = getSpecificPost(post)

            stamps = TimeStamp.objects.all().order_by('-pk')[first:last*sort:sort]
            #Get all stamps, order them bij latest, and then sort by interval

            dataRows = []

            for stamp in stamps:
                dataRow = [stamp]
                data = SensorData.objects.filter(relatedStamp_id=stamp.id)

                for row in data:
                    dataRow.append(row.data)

                dataRows.append(dataRow)

            sensors = SensorDescription.objects.all().order_by('pk')
            context = {'stamps' : dataRows, 'sensors':sensors, 'data':dataRows }
            #Sets the context for template calls


            return render(request, 'survey/stamp.html', context)
            #Renders webpage




    stamps = TimeStamp.objects.all().order_by('-pk')[::1]
    stamps = stamps[:100]
    #Get all stamps, order them bij latest, and then sort by interval

    dataRows = []

    for stamp in stamps:
        dataRow = [stamp]
        data = SensorData.objects.filter(relatedStamp_id=stamp.id)

        for row in data:
            dataRow.append(row.data)

        dataRows.append(dataRow)

    sensors = SensorDescription.objects.all().order_by('pk')
    context = {'stamps' : dataRows, 'sensors':sensors, 'data':dataRows }
    #Sets the context for template calls


    return render(request, 'survey/stamp.html', context)
    #Renders webpage


def timestampDetail(request,id):
    """
    Lists all measurements from a specific timestamp
    """
    relatedData = SensorData.objects.filter(relatedStamp_id = id)
    #Get all data with the related timestamp

    relatedStamp = get_object_or_404(TimeStamp, pk=id)
    #Get timestamp to display

    context = {'stampTime': relatedStamp.stamp.time(), 'stampDate':relatedStamp.stamp.date(),  'data' : relatedData}
    return render(request, 'survey/stampDetailed.html', context)


def generate(request):
    """
    Generate fake data, and redirect back to index

    A lot of data
    """
    current  = TimeStamp.objects.order_by('-pk')[0].stamp
    if current == 0:
        current = datetime.datetime.now()
    delta = datetime.timedelta(minutes=10)
    for x in range(0, 200):
        # get a timestamp

        timestampf = TimeStamp(stamp=current)
        timestampf.save()
        #Add timestamp to database

        sensors = SensorDescription.objects.all()
        #Get all available sensors

        random.seed(current)
        for sensor in sensors:
            fakeData = random.randint(1, 2000)

            newEntry = SensorData(relatedStamp=timestampf, relatedSensor=sensor, data=fakeData)

            newEntry.save()

        current += delta

    return index(request)


def download(request, amount = 0, interval = 0):
    """
    Either generates a .csv file, or
    """
    if request.GET:
        #Generate download data
        now = datetime.datetime.now()
        response = HttpResponse(content_type="text/csv")
        response['Content-Disposition'] = 'attachment; filename="%s.csv"' % str(now)

        writer = csv.writer(response, delimiter=';')

        dataRow = ['timestamp']

        stamps = TimeStamp.objects.all()[::int(request.GET['interval'])]
        stamps = stamps[:int(request.GET['amount'])]

        sensors = SensorDescription.objects.all()

        for sensor in sensors:
            dataRow.append(str(sensor) + (" (%s)" % sensor.unit))

        writer.writerow(dataRow)

        for stamp in stamps:
            dataRow = [str(stamp.stamp)]
            data = SensorData.objects.filter(relatedStamp=stamp).order_by("relatedSensor")

            for row in data:
                dataRow.append(row.data)


            writer.writerow(dataRow)
        return response
    else:
        stampCount = TimeStamp.objects.count()

        context = {'stampcount' : stampCount}

        return render(request, "survey/download.html", context)


def find(request):
    """
    Attempts to find a specific timestamp
    """
    return HttpResponse("In construction")

survey/templates/survey/base.html
{% load staticfiles %}

{% csrf_token %}
<!doctype html>
<html lang="en">
  <head>
      <meta charset="utf-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
      <meta name="description" content="" />
      <meta name="author" content="" />
      <title>{% block title %}Wijk van Morgen{% endblock %}</title>
      <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
      <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
    </head>

    <body>
      {% block navbar %}
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
          <!-- Mavbar Header -->
          <div class="navbar-header pull-right">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'survey:index' %}">Wijk van Morgen - Data</a>
          </div>

          <!-- Navbar Links -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'survey:index' %}">Home</a></li>
              <li><a href="{% url 'survey:generate' %}">Fake some Data</a></li>
                <li><a href="{% url 'survey:TimestampGeneral' %}">Stamps</a></li>
                <li><a href="{% url 'survey:InstrumentAll' %}">Instrument</a></li>
                <li><a href="{% url 'survey:Download' %}">Download</a></li>
                <!--
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><p class="navbar-text">Dit is een link</p></li>
                </ul>
              </li>
              -->
            </ul>
          </div>
        </nav>

      {% endblock navbar %}
      <div class="container">
        {% block content %}
        <div class="row">
          <div class="col-xs-6 col-xs-offset-3">
            <p>something went wrong!</p>
          </div>
        </div>
        {% endblock content %}
      </div>
 
      <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="{% static 'js/bootstrap.js' %}"></script>
      <script src="{% static 'js/jquery.js' %}"></script>

      {% block scripts %}
      <!-- ADDITIONAL -->
      {% endblock scripts %}
  </body>
</html>

survey/templates/survey/download.html
{%  extends 'survey/base.html' %}

{% csrf_token %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1>Download</h1>
        <p>Stel uw parameters op</p>
        <form role="form" method="get">
            <div class="form-group">
                <label for="amountInput">Hoeveel gegevens?</label>
                <p>Het maximale aantal meetpunten is {{ stampcount }}</p>
                <input type="datetime" class="form-control" name="amount" placeholder="{{ stampcount }}"></input>
            </div>
            <div class="form-group">
                <label>Interval</label>
                <select class="form-control" name="interval">
                    <option value="1">Tien minuten</option>
                    <option value="3">Half uur</option>
                    <option value="6">Uur</option>
                    <option value="18">Drie uur</option>
                    <option value="36">Zes uur</option>
                    <option value="72">12 uur</option>
                    <option value="144">Dagelijks</option>
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-success btn-block">Downloaden</button>
                <p></p>
            </div>
        </form>
    </div>
</div>
{%  endblock %}

survey/templates/survey/index.html
{% extends "survey/base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1>Welkom bij de wijk van morgen</h1>
        <p>De volgende data is gemeten op {{ stampDate }} om {{ stampTime}}</p>
        <table class="table table-hover">
            <tr>
                <th>Meetpunt</th>
                <th>Data</th>
                <th>Eenheid</th>
            </tr>
            {%  for row in data %}
            <tr>
                <td>{{ row.relatedSensor }} in {{ row.relatedSensor.unit }}</td>
                <td>{{ row.data }}</td>
                <td>{{ row.relatedSensor.unit  }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

survey/templates/survey/instrument.html
{%  extends 'survey/base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1>Instrumenten</h1>
        <p>Een lijst van alle instrumenten</p>
        <table class="table table-hover">
            <tr>
                <th>Naam</th>
                <th>Beschrijving</th>
                <th>Laats gemeten</th>
                <th>Eenheid</th>
                <th></th>
            </tr>
            {% for tool in instruments %}
            <a href="{% url 'survey:InstrumentDetailed' tool.id %}">
                <tr>
                    <td>{{ tool.name }}</td>
                    <td>{{ tool.description }}</td>
                    <td>
                        {% for row in data %}
                            {% if row.relatedSensor == tool %}
                            {{ row.data }}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ tool.unit }}</td>
                    <td><a href="{% url 'survey:InstrumentDetailed' tool.id %}">Bekijk</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{%  endblock %}

survey/templates/survey/instrumentDetail.html
{%  extends 'survey/base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1>{{ sensor.name }}</h1>
        <p>{{ sensor.description }}</p>

        <div id="specific" class="row">
            <div class="col-sm-4">
                <form method="post" action="{% url 'survey:InstrumentDetailed' sensor.id %}">

                    {% csrf_token %}

                    <div class="form-group" id="specific">
                        <label>Beginpunt</label>
                        <input type="number" name="start" class="form-control">
                        <label>Eindpunt</label>
                        <input type="number" name="end" class="form-control">
                        <label>Sorteren</label>
                        <input type="number" name="sorting" class="form-control">
                        <input type="hidden" name="action" value="specify">
                        <br />
                        <button class="btn btn-success btn-block" name="sort">Submit</button>
                    </div>
                </form>
            </div>

            <div class="col-sm-offset-8">
                <form method="post" action="{% url 'survey:InstrumentDetailed' sensor.id %}">
                    {% csrf_token %}

                    <div class="form-group">
                        <label>Begin</label>
                        <input type="number" class="form-control" name="first" value={{ first }}>
                        <label>Laatst</label>
                        <input type="number" class="form-control" name="last" value={{ last }}>
                        <label>Sort</label>
                        <input type="number" class="form-control" name="sorting" value="{{ sort }}">
                        <br />
                        <input type="hidden" name="action" value="download">
                        <button class="btn btn-success btn-block" name="download">Download deze data</button>
                     </div>
                </form>
            </div>
        </div>

        <button class="btn btn-default btn-block" id="showspec">Speciale details</button>
        <br />

        <table class="table table-hover">
            <tr>
                <th>Tijd</th>
                <th>{{ sensor.unit }}</th>
                <th>Andere data van tijd</th>
            </tr>
            {% for row in data %}
            <tr>
                <td>{{ row.relatedStamp.stamp|date:"D d M H:i" }}</td>
                <td>{{ row.data}}</td>
                <td><a href="{% url 'survey:TimestampDetailed' row.relatedStamp.id %}">Andere sensoren op dit tijdstip</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{%  endblock %}

{% block scripts %}
<script type="application/javascript">
    // On load
    $('document').ready(function(){
        $('#specific').hide();
    })

    // Laat alle details zien
    $('#showspec').click(function(){
        $('#specific').toggle("medium");
    })
</script>
{% endblock %}

survey/templates/survey/stamp.html
{%  extends 'survey/base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1>Timestamps</h1>
        <p>Alle stamps uit de afgelopen tijd</p>

        <div id="specific" class="row">
            <div class="col-sm-4">
                <form method="post" action="{% url 'survey:TimestampGeneral' %}">

                    {% csrf_token %}

                    <div class="form-group" id="specific">
                        <h2>Sorteren</h2>
                        <label>Beginpunt</label>
                        <input type="number" name="start" class="form-control">
                        <label>Eindpunt</label>
                        <input type="number" name="end" class="form-control">
                        <label>Sorteren</label>
                        <input type="number" name="sorting" class="form-control">
                        <input type="hidden" name="action" value="specify">
                        <br />
                        <button class="btn btn-success btn-block" name="sort">Submit</button>
                    </div>
                </form>
            </div>

            <div class="col-sm-offset-8">
                <form method="post" action="{% url 'survey:TimestampGeneral' %}">
                    {% csrf_token %}

                    <div class="form-group">
                        <h2>Downloaden</h2>
                        <label>Begin</label>
                        <input type="number" class="form-control" name="first" value={{ first }}>
                        <label>Laatst</label>
                        <input type="number" class="form-control" name="last" value={{ last }}>
                        <label>Sort</label>
                        <input type="number" class="form-control" name="sorting" value={{ sort }}>
                        <br />
                        <input type="hidden" name="action" value="download">
                        <button class="btn btn-success btn-block" name="download">Download deze data</button>
                     </div>
                </form>
            </div>
        </div>

        <button class="btn btn-default btn-block" id="showspec">Speciale details</button>

        <table class="table table-hover">
            <tr>
                <th>date</th>
                {% for sensor in sensors %}
                <th>{{ sensor }}</th>
                {%  endfor %}
                <th>Link</th>
            </tr>
            {% for stamppoint in stamps %}
            <tr>
                {% for item in stamppoint %}
                    {% if item.stamp %}
                        <td>{{ item.stamp|date:"D d N H:i" }}</td>
                    {% else %}
                        <td>{{ item }}</td>
                    {% endif %}
                {% endfor %}
                <td><a href="{% url 'survey:TimestampDetailed' stamppoint.0.id %}">Bekijk Detail</a></td>
            </tr>
            {% endfor %}
        <table>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="application/javascript">
    // On load
    $('document').ready(function(){
        $('#specific').hide();
    })

    // Laat alle details zien
    $('#showspec').click(function(){
        $('#specific').toggle("medium");
    })
</script>
{% endblock %}

survey/templates/survey/stampDetailed.html
{%  extends 'survey/base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1>Snapshot</h1>
        <p>Dit is een snapshot van {{ stampTime }} op {{ stampDate }}</p>
        <table class="table table-hover">
            <tr>
                <th>Sensor</th>
                <th>Data</th>
                <th>Links</th>
            </tr>
            {% for row in data %}
            <tr>
                <td>{{ row.relatedSensor}}</td>
                <td>{{ row.data }} {{ row.relatedSensor.unit }}</td>
                <td><a href="{% url 'survey:InstrumentDetailed' row.relatedSensor.id %}">Bekijk geschiedenis</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{%  endblock %}